### ISSUE TITLE
Datasourcing

### ISSUE THREAD

**Issue by Tommycore** [Tommycore/Smithy#1]
Content of any form should be modularisable in order to be easier to share and reuse. VS Code workspaces already allow to work with all kinds of files, and model a perfect example on how to implement database access. Similar to how VS Code allows to gather folders into a workspace, there needs to be an option to add data connections.

#### Workspaceconnection
A connection that is established in the current workspaceconfiguration.

#### Document
An accumulation of pairings between a name (called key) and a value.

#### Model
A definition what a document *must* entail, what it *may* entail, and what it *must not* entail. It's a contract that interfaces can use to guarantee certain criteria are met when exchanging arbitrary documents. A document can satisfy the definition of several different models at the same time, and a model can be used in different places.

#### Collection
A list of documents that all satisfy the same models.

#### Query
A request that should be answered with either 0 or more files or documents.

### Subsystems
- [ ] Connect to a database
- [ ] Disconnect from a database
- [ ] Activate a module in a database
- [ ] Deactivate a module in a database
- [ ] Query workspace
- [ ] Write in workspace
