### ISSUE TITLE
Modular Data Processing

### ISSUE THREAD

**Issue by Tommycore** [Tommycore/Smithy#2]
Machines are better suited to perform clearly defined, repetitive tasks. We just need to explain to them what to do. This system is intended to do exactly that: It provides a visual way to combine instructions into processes that can be applied to datasets.

#### Step
A step is a singular instruction. This may include executing multiple substeps. For example a step could be calculating the mean value of a set of numbers. Substeps would be adding all numbers and dividing the result by the amount of numbers added.

#### Atomic Step
An atomic step is a step that does not have any substeps. For example adding two numbers.

#### Pipeline
A set of instructions. For example a pipeline could be gathering all data points that have a weight value, calculate the mean weight, and write the result into a logfile.

#### Parameter
Variable input to a step. Parameters are exposed to the parent graph.

#### Graph
Visual representation of a pipeline.

> The difference between pipelines and steps is the perspective. A step in a pipeline becomes a pipeline itself when viewed on it's own graph. An atomic step on the other hand does not have it's own graph. It represents a piece of code.

### Subsystems
- [ ] Create a pipeline
- [ ] View a pipeline
- [ ] Instantiate atomic steps
- [ ] Remove a step in a pipeline
- [ ] Change parameters for a step
- [ ] Store pipeline as a template
- [ ] Instantiate template pipelines
- [ ] Reference steps in a pipeline
- [ ] Connect steps in a pipeline
- [ ] Disconnect steps in a pipeline
- [ ] Store a pipeline in it's own file
- [ ] Execute a pipeline
