### ISSUE TITLE
Content Layering

### ISSUE THREAD

**Issue by Tommycore** [Tommycore/Smithy#3]
This system is the base for localisation and themeing. Have some default data, add a language, add another language, exchange the default item icons with others and have Smithy build all combinations of languages and themes as you want.

#### Filelayer
A folder that contains referenceable files. Can be empty.

#### Documentlayer
A list of referenceable collections. Can be empty.

#### Contentlayer
A file- or documentlayer.

### Subsystems
- [ ] Add content layer
- [ ] Remove content layer
- [ ] Add variation for content layer

Subsystems don't need to be in any specific order.
